# Generated by Django 4.0.5 on 2022-06-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='category.category')),
            ],
            options={
                'db_table': 'apps_reports',
            },
        ),
        migrations.CreateModel(
            name='Reports_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=99)),
                ('year', models.CharField(max_length=99)),
            ],
            options={
                'db_table': 'apps_date',
            },
        ),
        migrations.CreateModel(
            name='Reports_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True)),
            ],
            options={
                'db_table': 'apps_departments',
            },
        ),
        migrations.CreateModel(
            name='Reports_Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True)),
                ('quarter', models.CharField(max_length=99)),
            ],
            options={
                'db_table': 'apps_month',
            },
        ),
        migrations.CreateModel(
            name='Reports_Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_amount', models.CharField(max_length=99)),
                ('total_including_tax', models.CharField(max_length=99)),
                ('total_excluding_tax', models.CharField(max_length=99)),
                ('date', models.ForeignKey(default='no value', on_delete=django.db.models.deletion.CASCADE, related_name='Revenue_Date', to='reports.reports_date')),
                ('departments', models.ForeignKey(default='no value', on_delete=django.db.models.deletion.CASCADE, related_name='Revenue_Departments', to='reports.reports_departments')),
                ('reports', models.ForeignKey(default='no value', on_delete=django.db.models.deletion.CASCADE, related_name='Revenue_Reports', to='reports.reports')),
            ],
            options={
                'db_table': 'apps_reports_revenue',
            },
        ),
        migrations.CreateModel(
            name='Reports_Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.CharField(max_length=99)),
                ('net_profit', models.CharField(max_length=99)),
                ('gross_profit', models.CharField(max_length=99)),
                ('date', models.ForeignKey(default='no value', on_delete=django.db.models.deletion.CASCADE, related_name='Profit_Date', to='reports.reports_date')),
                ('departments', models.ForeignKey(default='no value', on_delete=django.db.models.deletion.CASCADE, related_name='Profit_Departments', to='reports.reports_departments')),
                ('reports', models.ForeignKey(default='no value', on_delete=django.db.models.deletion.CASCADE, related_name='Profit_Reports', to='reports.reports')),
            ],
            options={
                'db_table': 'apps_reports_profit',
            },
        ),
        migrations.AddField(
            model_name='reports_date',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reports_Month', to='reports.reports_month'),
        ),
    ]
