# Generated by Django 4.0.5 on 2022-06-19 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='name',
            new_name='reports_name',
        ),
        migrations.RenameField(
            model_name='reports_departments',
            old_name='name',
            new_name='departments_name',
        ),
        migrations.RenameField(
            model_name='reports_month',
            old_name='name',
            new_name='month_name',
        ),
    ]
